services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5005:5432"
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: etl-pipeline
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql # Mount initialization script
volumes:
  postgres_data:
